### ISSUE TITLE
Model Cleanup

### ISSUE THREAD

**Issue by dinoocch** [ConstellationApps/TicketBox#22]
Just a few cleanup things from a database perspective...

# General Statements
* Is there a reason you use CharFields instead of TextFields?
* `blank=False` is implicit, so you don't need to state it

# Specific Comments
https://github.com/ConstellationApps/TicketBox/blob/master/constellation_ticketbox/models.py#L8
```python
ticket = models.ForeignKey('Ticket', blank=True, null=True)
owner = models.ForeignKey(User)
author = models.CharField(max_length=128, default='Anonymous')
```
* on the ticket field definition blank and null are not needed unless there's a good reason...
* why set owner and author?

https://github.com/ConstellationApps/TicketBox/blob/master/constellation_ticketbox/models.py#L19
```python
owner = models.ForeignKey(User)
author = models.CharField(max_length=128, default='Anonymous')
```

https://github.com/ConstellationApps/TicketBox/blob/master/constellation_ticketbox/models.py#L32
This is unnecessary I believe (you already have it in the model)

https://github.com/ConstellationApps/TicketBox/blob/master/constellation_ticketbox/models.py#L25
You could do an integer field instead

https://github.com/ConstellationApps/TicketBox/blob/master/constellation_ticketbox/models.py#L28
This could be combined with status

**Comment by tdorianh** [comment]
> Is there a reason you use CharFields instead of TextFields?

CharField is used for fields where users should be able to enter their own text, and be subject to a character limit (to prevent a title/status message from being paragraphs long). (Such as for 'Status' and 'Title'). Django's documentation says to use CharFields for smaller strings and TextFields for large text.

> why set owner and author?

Owner and Author were both set as part of a workaround to pass the Ticket view usernames of the reply/ticket owners. It was only able to access user ID. I am currently revising this to only use the 'owner' field.

> You could do an integer field instead

Title is a CharField and not an IntegerField because it refers to a short summary/title of the ticket, not a ticket number.

> This could be combined with status

Status is separate from other fields because it is a message regarding the status of the ticket; such as, 'in progress', 'open', 'will be resolved in the future but not now', 'being considered', etc. 

Everything else (including the separate author/owner fields issue) is being corrected right now.
